### ISSUE TITLE
发包异常

### ISSUE THREAD

**Issue by silencelbl** [trpc-group/tnet#20]
在测试过程中，服务器都使用tnet作为网络库，A进程使用tnet.DialTCP连接B进程服务器，当大量客户端连接和A进程开始交互后，A进程频繁和B进程进行消息通信，在一段时间后，B进程解包失败。
通过日志分析排查，结合使用tcpdump抓包发现，B进程收到了一个异常消息包，通过tcpdump可以看到，消息是从A进程发送过来，但是在A进程的Send方法中，并没有找到发送该消息的日志和信息。
A进程消息收发也没有异常和报错，什么情况会导致这种现象发生，从tcpdump抓到的包看，疑似是A进程的DialTCP连接底层发送了其他客户端连接上的数据，导致的B进程解包失败。
目前从代码上看DailTCP和Service使用的是同一个TCPHandler回调函数。

**Comment by WineChord** [comment]
Hello, could you please provide a reproducible repository and specify your working environment, including the Go version, operating system version, and architecture?

**Comment by silencelbl** [comment]
Go version: 1.21.3
Linux version 3.10.0-1160.66.1.el7.x86_64

**Comment by silencelbl** [comment]
今天再次测试，发现有串包现象，日志看到send接口消息是发送到一个client连接的，但是B进程收到了消息，日志中确实没有发送到B进行的痕迹。
测试环境：8C16G 腾讯云服务器 Linux 3.10.0-1160.66.1.el7.x86_64
代码库：trpc.group/trpc-go/tnet v1.0.0
Go版本：version go1.21.3 linux/amd64
tnet.SetNumpollers(runtime.NumCPU())
-----------------------------------------------------------------------------------------
A进程创建了2个TCPService，同时会调用tnet.DialTCP连接B进程
B进程创建了1个TCPService（接收A进程的消息）
Service参数设置：WithSafeWrite(true), WithNonBlocking(true)
TCPHander方法，Service和DialTCP绑定的同一个回调函数


在测试过程中，client连接到A进程，A进程触发逻辑转发消息到B进程，在client个数不多的情况，不会触发异常问题，当client达到一定量后，异常必现。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "trpc-group/tnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月16日(星期六) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [trpc-group/tnet] 发包异常 (Issue #20)





 
Hello, could you please provide a reproducible repository and specify your working environment, including the Go version, operating system version, and architecture?

**Comment by silencelbl** [comment]
Is anyone looking into this issue?

**Comment by WineChord** [comment]
@silencelbl Could you please directly provide a reproducible github repo? You can push your code to your public repository and provide a link here.

**Comment by WineChord** [comment]
I can think of a common scenario where this issue might occur. The root cause could be port reuse, where multiple processes are listening on the same port. To troubleshoot this, you can check if there are multiple processes using the same port.

**Comment by WineChord** [comment]
@silencelbl I still believe it would be best if you could directly provide a minimal reproducible code repository. This would minimize the communication effort required. Otherwise, I would need to ask for details about each issue mentioned in your description in order to reproduce them accurately. Could you please provide a repository? It would save time for both of us. Thank you.

**Comment by silencelbl** [comment]
> @silencelbl我仍然相信，如果您能够直接提供一个最小的可复制代码存储库，那将是最好的。这将最大限度地减少所需的沟通工作。否则，我需要询问您描述中提到的每个问题的详细信息，以便准确地重现它们。您能提供一个存储库吗？这将为我们俩节省时间。谢谢。

这两天，我尽量抽时间整理一份可复现问题的代码，可否添加一个联系方式？

**Comment by silencelbl** [comment]
> @silencelbl I still believe it would be best if you could directly provide a minimal reproducible code repository. This would minimize the communication effort required. Otherwise, I would need to ask for details about each issue mentioned in your description in order to reproduce them accurately. Could you please provide a repository? It would save time for both of us. Thank you.

这两天我尽量抽空整理份能复现问题的代码，可否添加个VX？

**Comment by silencelbl** [comment]
> I can think of a common scenario where this issue might occur. The root cause could be port reuse, where multiple processes are listening on the same port. To troubleshoot this, you can check if there are multiple processes using the same port.

测试环境虽然在一台机子上启动了多个服务进程，client是在单独的施压机上单独运行，各服务进程监听端口是检查过的，我们在tnet测试异常后，切换会原生net包代码，问题不在复现，后面我整理下代码，提供一份给你看看。

**Comment by silencelbl** [comment]
> @silencelbl I still believe it would be best if you could directly provide a minimal reproducible code repository. This would minimize the communication effort required. Otherwise, I would need to ask for details about each issue mentioned in your description in order to reproduce them accurately. Could you please provide a repository? It would save time for both of us. Thank you.

复现代码已上传，我邀请了你

**Comment by WineChord** [comment]
> > @silencelbl I still believe it would be best if you could directly provide a minimal reproducible code repository. This would minimize the communication effort required. Otherwise, I would need to ask for details about each issue mentioned in your description in order to reproduce them accurately. Could you please provide a repository? It would save time for both of us. Thank you.
> 
> 复现代码已上传，我邀请了你

OK, I've received the invitation. I am working on it.

**Comment by WineChord** [comment]
@silencelbl, I have figured out the solution. You have reused the buffer that is provided to tnet.Conn.Writev. But you only provide SafeWrite option to the server side. You should also enable the SafeWrite option on the client side:

![image](https://github.com/trpc-group/tnet/assets/20353612/f7fb73df-2ed9-4c8c-ae3e-1a0ed88dfed1)

**Comment by silencelbl** [comment]
> @silencelbl, I have figured out the solution. You have reused the buffer that is provided to tnet.Conn.Writev. But you only provide SafeWrite option to the server side. You should also enable the SafeWrite option on the client side:
> 
> ![image](https://private-user-images.githubusercontent.com/20353612/292842360-f7fb73df-2ed9-4c8c-ae3e-1a0ed88dfed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODMzMDUsIm5iZiI6MTcwMzc4MzAwNSwicGF0aCI6Ii8yMDM1MzYxMi8yOTI4NDIzNjAtZjdmYjczZGYtMmVkOS00YzhjLWFlM2UtMWEwZWQ4OGRmZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE3MDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNWI4ODlkNzM0N2E4Y2YzYmY5YzBjNDY1ZDYxMjM2Y2I4ZGNkZmE4YTNiM2U3NzkxNGI2Yjc1YzA2OTI3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T3YGgn72t4Yf2Orsx2KJHZS8D72C1iL20SoJFwkPbfY)

3Q，问题得以解决，测试过程无再现此问题！在同一进程中的conn/tcp/udp都应设置safeWrite对吧@WineChord

**Comment by WineChord** [comment]
> > @silencelbl, I have figured out the solution. You have reused the buffer that is provided to tnet.Conn.Writev. But you only provide SafeWrite option to the server side. You should also enable the SafeWrite option on the client side:
> > ![image](https://private-user-images.githubusercontent.com/20353612/292842360-f7fb73df-2ed9-4c8c-ae3e-1a0ed88dfed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODMzMDUsIm5iZiI6MTcwMzc4MzAwNSwicGF0aCI6Ii8yMDM1MzYxMi8yOTI4NDIzNjAtZjdmYjczZGYtMmVkOS00YzhjLWFlM2UtMWEwZWQ4OGRmZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE3MDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNWI4ODlkNzM0N2E4Y2YzYmY5YzBjNDY1ZDYxMjM2Y2I4ZGNkZmE4YTNiM2U3NzkxNGI2Yjc1YzA2OTI3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T3YGgn72t4Yf2Orsx2KJHZS8D72C1iL20SoJFwkPbfY)
> 
> 3Q，问题得以解决，测试过程无再现此问题！在同一进程中的conn/tcp/udp都应设置safeWrite对吧@WineChord

As long as you manage the buffer passed to writev on your own, you should always set safewrite to true.
